version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  stdout:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(message)s"
    log_colors:
      DEBUG: "cyan"
      INFO: "green"
      WARNING: "yellow"
      ERROR: "red"
      CRITICAL: "bold_red"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: stdout
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/edwige.log

loggers:
  main_logger:
    level: INFO
    handlers: [console, file]
    propagate: no
  spotify_logger:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [file]
