version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  stdout:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s[%(filename)s:%(lineno)d] %(levelname)s | %(message)s"
    log_colors:
      DEBUG: "cyan"
      INFO: "green"
      WARNING: "yellow"
      ERROR: "red"
      CRITICAL: "bold_red"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: stdout
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/edwige.log
    encoding: utf-8

  naruto_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/naruto.log
    encoding: utf-8

loggers:
  main:
    level: DEBUG
    handlers: [console, file]
    propagate: no
    
  naruto:
    level: DEBUG
    handlers: [console, naruto_file]
    propagate: no
    
root:
  level: DEBUG
  handlers: [file]
