[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning:importlib._bootstrap
    ignore::DeprecationWarning:builtin

[coverage:run]
source = owlai
omit = 
    */tests/*
    */__init__.py
    */setup.py
    */conftest.py

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise NotImplementedError
    if __name__ == .__main__.:
    pass
    raise ImportError
    except ImportError:
    raise NotImplementedError
    if TYPE_CHECKING:
    @abstractmethod
    raise NotImplementedError
    def _run
    def _arun

[coverage:html]
directory = coverage_html 