version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s %(extra)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/owlai.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  owlai:
    level: INFO
    handlers: [console, file]
    propagate: false

  owlai.model:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  owlai.agent:
    level: INFO
    handlers: [console, file]
    propagate: false

  owlai.tools:
    level: INFO
    handlers: [console, file]
    propagate: false 